# Generated by Django 4.0.4 on 2022-04-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthName', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='paid_this_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payments',
            name='Month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_api.month'),
        ),
    ]
