# Generated by Django 4.0.4 on 2022-04-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_api', '0002_month_tenant_paid_this_month_alter_payments_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='Month',
        ),
        migrations.AddField(
            model_name='payments',
            name='monthName',
            field=models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], default='April', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
