# Generated by Django 4.0.4 on 2022-05-10 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent_api', '0003_remove_payments_month_payments_monthname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('Month_ID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Month_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('Year_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='house',
            old_name='Apartment',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='paid_this_month',
            new_name='Active',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='monthName',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='Landlord_code',
        ),
        migrations.AddField(
            model_name='house',
            name='Cleared_payment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='Email',
            field=models.CharField(default='khanbrackly@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='End_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='Start_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='mode_of_payment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='House_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_api.house'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Rent_price', models.FloatField()),
                ('Opening_balance', models.FloatField()),
                ('Closing_balance', models.FloatField()),
                ('Total_Payments', models.FloatField()),
                ('House_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_api.house')),
                ('Month_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_api.month')),
                ('Year_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_api.year')),
            ],
        ),
    ]
