# Generated by Django 4.0.4 on 2022-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_api', '0005_remove_invoice_rent_price_house_rent_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
